import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

// Sans font
const sans = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className={`${sans.variable} h-full`}>{children}</body>
    </html>
  );
}
